export enum MessageCode {
  MOVIE_ALREADY_IN_LIST = "MOVIE_ALREADY_IN_LIST",
  MOVIE_ADDED_TO_LIST = "MOVIE_ADDED_TO_LIST",
  MOVIE_REMOVED_FROM_LIST = "MOVIE_REMOVED_FROM_LIST",
  ERROR_ADD_MOVIE = "ERROR_ADD_MOVIE",
  ERROR_REMOVE_MOVIE = "ERROR_REMOVE_MOVIE",
}
