export const TOKENS = {
  IHttpClient: "IHttpClient",
  IStorageService: "IStorageService",
  IConfigService: "IConfigService",
  IMovieRepository: "IMovieRepository",
  IGetUserListRepository: "IGetUserListRepository",
  IAddMovieToUserListRepository: "IAddMovieToUserListRepository",
  IRemoveMovieFromUserListRepository: "IRemoveMovieFromUserListRepository",
  MovieRemoteDataSource: "MovieRemoteDataSource",
  MovieLocalDataSource: "MovieLocalDataSource",
  GetMoviesByCategory: "GetMoviesByCategory",
  GetMovieDetails: "GetMovieDetails",
  GetUserList: "GetUserList",
  AddMovieToUserList: "AddMovieToUserList",
  RemoveMovieFromUserList: "RemoveMovieFromUserList",
};
