export const TOKENS = {
  IHttpClient: "IHttpClient",
  IStorageService: "IStorageService",
  IConfigService: "IConfigService",
  IGetMoviesByCategoryRepository: "IGetMoviesByCategoryRepository",
  IGetMovieDetailsRepository: "IGetMovieDetailsRepository",
  IGetUserListRepository: "IGetUserListRepository",
  IAddMovieToUserListRepository: "IAddMovieToUserListRepository",
  IRemoveMovieFromUserListRepository: "IRemoveMovieFromUserListRepository",
  IMovieRemoteDataSource: "IMovieRemoteDataSource",
  IMovieLocalDataSource: "IMovieLocalDataSource",
  IGetMoviesByCategory: "IGetMoviesByCategory",
  IGetMovieDetails: "IGetMovieDetails",
  IGetUserList: "IGetUserList",
  IAddMovieToUserList: "IAddMovieToUserList",
  IRemoveMovieFromUserList: "IRemoveMovieFromUserList",
};
