/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './presentation/routes/__root'
import { Route as IndexRouteImport } from './presentation/routes/index'
import { Route as DetailsUserListRouteImport } from './presentation/routes/details.userList'
import { Route as DetailsIdRouteImport } from './presentation/routes/details.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DetailsUserListRoute = DetailsUserListRouteImport.update({
  id: '/details/userList',
  path: '/details/userList',
  getParentRoute: () => rootRouteImport,
} as any)
const DetailsIdRoute = DetailsIdRouteImport.update({
  id: '/details/$id',
  path: '/details/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/details/$id': typeof DetailsIdRoute
  '/details/userList': typeof DetailsUserListRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/details/$id': typeof DetailsIdRoute
  '/details/userList': typeof DetailsUserListRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/details/$id': typeof DetailsIdRoute
  '/details/userList': typeof DetailsUserListRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/details/$id' | '/details/userList'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/details/$id' | '/details/userList'
  id: '__root__' | '/' | '/details/$id' | '/details/userList'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DetailsIdRoute: typeof DetailsIdRoute
  DetailsUserListRoute: typeof DetailsUserListRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/details/userList': {
      id: '/details/userList'
      path: '/details/userList'
      fullPath: '/details/userList'
      preLoaderRoute: typeof DetailsUserListRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/details/$id': {
      id: '/details/$id'
      path: '/details/$id'
      fullPath: '/details/$id'
      preLoaderRoute: typeof DetailsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DetailsIdRoute: DetailsIdRoute,
  DetailsUserListRoute: DetailsUserListRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
